spring:
    profiles:
        active: default
    
    jpa.hibernate.ddl-auto: update   
    datasource:
     url: jdbc:mysql://localhost:3306/reaktor_timetableserver
     username: root
     password: toor
     driver-class-name: com.mysql.cj.jdbc.Driver
     hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
 
logging:
  pattern.console: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'
  level.org.hibernate.SQL: debug
  level: debug
server:
    port: 8088
urlCors: http://localhost:5000, http://localhost:5500, http://localhost:5173, http://192.168.6.40:5173, https://alvaroo611.github.io